version: '3.8'

services:
  ethereum-explorer-frontend:
    image: node:18-alpine
    container_name: ethereum-explorer-frontend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=development
      - PORT=8888
      - HOST=0.0.0.0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    command: >
      sh -c "npm install && npm start"
    networks:
      - ethereum-explorer-network

  ethereum-explorer-backend:
    image: openjdk:17-jdk-slim
    container_name: ethereum-explorer-backend
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
    command: >
      sh -c "[ -f target/SmartContractExtractor-1.0.jar ] && java -jar target/SmartContractExtractor-1.0.jar || echo 'Backend JAR not found, skipping'"
    networks:
      - ethereum-explorer-network

networks:
  ethereum-explorer-network:
    driver: bridge
